services:
  subtitler:
    image: subtitler:latest
    container_name: subtitler
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MINIO_HOST=minio
      - MINIO_ACCESS_KEY=nH5HC71L74yocEF7kVSR
      - MINIO_SECRET_KEY=bvKIDrJ5hxoii0FfhkPfnkjCCDH5Vbc6cvBBo6Le
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=subtitler
      - POSTGRES_USERNAME=subtitler
      - POSTGRES_PASSWORD=subtitler
    volumes:
      - ./subtitler/config:/config
    ports:
      - 6768:6767
    restart: unless-stopped
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_PASSWORD: subtitler
      POSTGRES_USER: subtitler
      POSTGRES_DB: subtitler
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
  
  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ./radarr/data:/config
  #     - ./downloads/complete:/Users/tourist/Untitled/bazarr/downloads/complete
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped


  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ./sonarr/data:/config
  #     - ./sonarr/downloads:/downloads
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped
  
  # transmission:
  #   image: lscr.io/linuxserver/transmission:latest
  #   container_name: transmission
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     # - TRANSMISSION_WEB_HOME= #optional
  #     # - USER= #optional
  #     # - PASS= #optional
  #     # - WHITELIST= #optional
  #     # - PEERPORT= #optional
  #     # - HOST_WHITELIST= #optional
  #   volumes:
  #     - ./transmission/data:/config
  #     - ./downloads:/downloads
  #     - ./transmission/watch:/watch
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   restart: unless-stopped
